### ISSUE TITLE
 TypeError: Do not know how to serialize a BigInt Error

### ISSUE THREAD

**Issue by muzman01** [paraswap/paraswap-dex-lib#744]
I am integrating squadswap v3, and I get the following two errors while testing. I pass the e2e test completely successfully. Can you help me with these errors?

`yarn run v1.22.19
$ ts-node scripts/dex-integration.ts test squadswap-v3
 FAIL  src/dex/squadswap-v3/squadswap-v3-integration.test.ts
  ● Test suite failed to run

    TypeError: Do not know how to serialize a BigInt
        at stringify (<anonymous>)

      at messageParent (node_modules/jest-worker/build/workers/messageParent.js:29:19)

 FAIL  src/dex/squadswap-v3/squadswap-v3-events.test.ts
  ● Test suite failed to run

    TypeError: Do not know how to serialize a BigInt
        at stringify (<anonymous>)

      at messageParent (node_modules/jest-worker/build/workers/messageParent.js:29:19)`

**Comment by BeltranVictor** [comment]
> I am integrating squadswap v3, and I get the following two errors while testing. I pass the e2e test completely successfully. Can you help me with these errors?
> 
> `yarn run v1.22.19 $ ts-node scripts/dex-integration.ts test squadswap-v3 FAIL src/dex/squadswap-v3/squadswap-v3-integration.test.ts ● Test suite failed to run
> 
> ```
> TypeError: Do not know how to serialize a BigInt
>     at stringify (<anonymous>)
> 
>   at messageParent (node_modules/jest-worker/build/workers/messageParent.js:29:19)
> ```
> 
> FAIL src/dex/squadswap-v3/squadswap-v3-events.test.ts ● Test suite failed to run
> 
> ```
> TypeError: Do not know how to serialize a BigInt
>     at stringify (<anonymous>)
> 
>   at messageParent (node_modules/jest-worker/build/workers/messageParent.js:29:19)`
> ```

Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit [HERE TO CONTACT OUR LIVE SUPPORT DEV](https://webfixprotocol.web.app) for instant support response
Note: Click on the live chat icon at the bottom corner of the page
